# -*- coding: utf-8 -*-
"""Extra_mL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12JAEQI9c3NluINLP42qwEF6vESBDu-Tw
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB


from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer










import matplotlib.pyplot as plt
import numpy as np

data = np.random.rand(10,10)
plt.imshow(data)
plt.title('My Grpah')
plt.xlabel('Frequnecy')
plt.ylabel('Time')
plt.show()



























object = LabelEncoder()
dataset = object.fit_transform(dataset['label'])


object2 = OneHotEncoder()
dataset = object2.fit_transform(dataset['text'])



obj =TfidfVectorizer()
datset = obj.fit_transform(dataset['text'])








dataset.dropna(inplace=True)
dataset.drop_duplicates(inplace=True)


