# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqUN6docvDer0Zj1VZOcfhVamJuE-yaT
"""

v1 = 250
print(type(v1))
print(v1)
print()

v2 = 28 % 5
print(type(v2))
print(v2)
print()

v3 = 2.5e2
print(type(v3))
print(v3)
print()

v4 = 3e5
print(type(v4))
print(v4)
print()

v5 = 3 * 10**5
print(type(v5))
print(v5)
print()

v6 = 20 + 35 * 2
print(type(v6))
print(v6)
print()

# Why is this different from (20 + 35) * 2?
# because this would add the values first and then multiply by 2


v7 = 2 / 3 * 3
print(type(v7))
print(v7)
print()

v8 = 2 // 3 * 3
print(type(v8))
print(v8)
print()
# Why is this different from 2 / 3 * 3?
#because regular division keeps fractions, but floor division removes the decimal


v9 = 25 - 5 * 2 - 9

print(type(v9))
print(v9)

#Is this different from ((25 - 5) * 2) - 9 and/or 25 - ((5 * 2) - 9)? Why?
# yes it is different because of how the brackets change precedence and forces the equation to subtract first

flavors = ['vanilla', 'chocolate', 'strawberry', 'pistachio']
sauces = ['caramel', 'butterscotch', 'chocolate']

for flavor in flavors:
    for sauce in sauces:
        print(flavor + " ice cream sundae with " + sauce + " sauce")

def triangle():
    value = 1
    row = 1
    while row <= 10:
        column = 1
        while column <= row:
            if column != row:
                print(value, ' ', sep = '', end = '')
            else:
                print(value)
            value = value + 1
            column = column + 1
        row = row + 1

triangle()

def cube(value):
  return value**3


cube(5)

def factorial(value):
  if value<0:
    print("Non negative integers allowed only")
    return
  elif value == 0 or value == 1:
    return 1
  else:
    temp = value -1
    while temp!=0:
      value  = value * temp
      temp -= 1
    return value

factorial(-1)

def count_pattern(pattern, mylist):
    count = 0
    n = len(pattern)

    for i in range(len(mylist)):
        if i + n <= len(mylist):
            segment = mylist[i:i+n]
            if segment == pattern:
                count += 1

    return count



count_pattern(('a', 'b', 'a'), ('g', 'a', 'b', 'a', 'b',
'a','b', 'a'))

num = int(input("Enter a number: "))

for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("Select operation you wanna perform: + , - , * , /")

operator = input("Enter your choice of operation: ")

if operator == '+':
    print("result is", num1 + num2)
elif operator == '-':
    print("result is", num1 - num2)
elif operator == '*':
    print("result is", num1 * num2)
elif operator == '/':
    print("result is", num1 / num2)

else:
    print("Invalid choice! Please select a valid operator.")

sentence = input("Enter a sentence: ")

words = sentence.split()

words.sort()

length  = len(words)

print(" the sorted words are:")
for i in range(length):
    print(words[i])

class RomanConverter:
    def to_roman(self, num):
        values = [1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1]
        symbols = ["M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"]

        result = ""
        for i in range(len(values)):
            while num >= values[i]:
                result += symbols[i]
                num -= values[i]
        return result

converter = RomanConverter()
print(converter.to_roman(58))
print(converter.to_roman(1994))

class IndicesFinder:
  def find(numbers, target):

    for i in range(len(numbers)):
      for j in range(len(numbers)):
        if  numbers[i] + numbers[j] == target:
            return [i, j]


hehe = IndicesFinder
hehe.find([10,20,10,40,50,60,70],50)

class findTriplets:
  def find_trip(numbers):

    for i in range(len(numbers)):
      for j in range(len(numbers)):
        for k in range(len(numbers)):
          if i != j and i != k and numbers[i]+numbers[j]+numbers[k]==0:
            return [numbers[i],numbers[j],numbers[k]]


finder = findTriplets
finder.find_trip([-25, -10, -7, -3, 2, 4, 8, 10])

class StringReverse:
  def rev(the_string):
    for stringg in reversed(the_string):
      print(the_string, end = '')

count_string = "i study in ucp"
count = 0
for string in count_string:
  count += 1
print(count)

def calculator_two(a, b, op='addition', data_type='float'):
    if op == 'addition':
        result = a + b
    elif op == 'subtraction':
        result = a - b
    elif op == 'multiplication':
        result = a * b
    elif op == 'division':
        result = a / b

    if data_type == 'integer':
        return round(result)
    else:
        return result

print(calculator_two(5, 3))
print(calculator_two(5, 3, 'division', 'integer'))

class Numbers:
    MULTIPLIER = 5

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def add(self):
        return self.x + self.y

    def multiply(cls, a):
        return a * cls.MULTIPLIER

    def subtract(b, c):
        return b - c

    def value(self):
        return (self.x, self.y)

    def value(self, xy_tuple):
        self.x, self.y = xy_tuple

    def value(self):
        self.x = 0
        self.y = 0