# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F_kh7zmKMZcNOqCj9GGw7HJ7UL2tPKMD
"""

# graph with actual cost
graph = {
    'CS': {'ITC': 65, 'PF': 68, 'XC': 67},
    'ITC': {'OOP': 35, 'DSA': 75, 'PF': 55},
    'PF': {'LA': 29, 'DS': 21},
    'OOP': {'DSA': 35, 'CCN': 29},
    'DSA': {'CCN': 25, 'LA': 32, 'DAA': 35},
    'XC': {'TOA': 36, 'DS': 22},
    'CCN': {'ML': 55, 'AI': 38, 'DAA': 50},
    'ML': {'FYP': 35},
    'AI': {'FYP': 85, 'WEB': 22},
    'LA': {'DAA': 35},
    'DAA': {'AI': 32},
    'DS': {'DB': 27, 'TOA': 32},
    'DB': {'DAA': 35, 'TOA': 35, 'WEB': 66},
    'TOA': {'MAD': 39, 'WEB': 62},
    'WEB': {'AI': 22, 'MAD': 62, 'FYP': 41},
    'MAD': {'FYP': 22},
    'FYP': {}
}
# heuristic value for graph
H_graph = {
    'CS': 26,
    'ITC': 22,
    'PF': 21,
    'OOP': 19,
    'DSA': 20,
    'XC': 23,
    'CCN': 15,
    'ML': 12,
    'AI': 9,
    'LA': 18,
    'DAA': 14,
    'DS': 16,
    'DB': 14,
    'TOA': 15,
    'WEB': 10,
    'MAD': 13,
    'FYP': 0
}
# A* algorithm to maximize incentives and minimize no. of weeks
def A_star(start, goals, graph, heuristic):
    total_cost = 0
    current_path = [start]
    visited_nodes = []
    open_list = [total_cost, current_path]

    while open_list:
        i = 0
        best_index = 0

        while i < len(open_list):
            best_cost = open_list[best_index]
            best_path = open_list[best_index + 1]
            best_node = best_path[-1]
            best_f_score = best_cost + heuristic[best_node]

            current_cost = open_list[i]
            checking_path = open_list[i + 1]
            checking_node = checking_path[-1]
            checking_f_score = current_cost + heuristic[checking_node]

            if best_f_score > checking_f_score:
                best_index = i
            i = i + 2

        total_cost = open_list.pop(best_index)
        current_path = open_list.pop(best_index)
        current_node = current_path[-1]

        if current_node not in visited_nodes:
            visited_nodes.append(current_node)

        if current_node in goals:
            return current_path, total_cost

        for next_node in graph[current_node].keys():
            if next_node not in visited_nodes:
                new_path = list(current_path)
                new_path.append(next_node)
                updated_cost = total_cost - graph[current_node][next_node]
                open_list.append(updated_cost)
                open_list.append(new_path)

    return None, float('inf')


start = 'CS'
goal_nodes = ['CCN'] #you can add multiple goals here

print("Running super mysterious algorithm to maximize incentives and minimize weeks...\n")

path, negative_cost = A_star(start, goal_nodes, graph, H_graph)

if path:
    print("Optimal path:", ' -> '.join(path))
    print(f"incentives earned: {-negative_cost}")

    weeks_used = H_graph[path[-1]]

    print(f"Weeks remaining when goal is reached: {weeks_used}")
    print(f"Goal node reached: {path[-1]}")
    print()
    print("Path breakdown:")
    for i in range(len(path) - 1):
        from_node = path[i]
        to_node = path[i + 1]
        incentive = graph[from_node][to_node]
        weeks = H_graph[to_node]
        print(f"  {from_node} -> {to_node}: +{incentive} incentives (weeks left: {weeks})")
else:
    print("No path found to any goal node!")