# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1waTTl4wTpj1m94ymPvHEAczcObK2SUh8
"""

def selection_sort(items):
    """Sorts a list of items into ascending order using the selection sort algorithm."""
    for step in range(len(items)):
        location_of_smallest = step
        for location in range(step, len(items)):
            if items[location] < items[location_of_smallest]:
                location_of_smallest = location

        items[step], items[location_of_smallest] = items[location_of_smallest], items[step]

def merge(left, right):

    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    while i < len(left):
        result.append(left[i])
        i += 1

    while j < len(right):
        result.append(right[j])
        j += 1

    return result


def merge_sort(arr):
    if len(arr) <= 1:
        return arr

    queue = [[x] for x in arr]

    while len(queue) > 1:
        left = queue.pop(0)
        right = queue.pop(0)

        merged = merge(left, right)
        queue.append(merged)

    return queue[0] if queue else []



listt = [5,6,7,2,46,3,8,1,7,9,3,2,7,94]
print(merge_sort(listt))

# we just keep swapping neighbors that are out of order until everything's sorted.

# Starting with: P, Y, T, H, O, N

# First:
# P and Y are good (P comes before Y)
# Y and T - T should come before Y, swap them: P, T, Y, H, O, N
# Y and H - H comes first, swap: P, T, H, Y, O, N
# Y and O - O comes first, swap: P, T, H, O, Y, N
# Y and N - N comes first, swap: P, T, H, O, N, Y

# Second pass:
# P and T are fine
# T and H - H comes first, swap: P, H, T, O, N, Y
# T and O - O comes first, swap: P, H, O, T, N, Y
# T and N - N comes first, swap: P, H, O, N, T, Y
# T and Y are fine

# Third pass:
# P and H - H comes first, swap: H, P, O, N, T, Y
# P and O - O comes first, swap: H, O, P, N, T, Y
# P and N - N comes first, swap: H, O, N, P, T, Y
# Rest is ok

# Fourth pass:
# H and O are fine
# O and N - N comes first, swap: H, N, O, P, T, Y
# Final list: H, N, O, P, T, Y

# Selection Sort
# find the smallest thing and put it up front, then repeat.

# Start: P, Y, T, H, O, N

# Look for smallest
# Swap P and H: H, Y, T, P, O, N

# Now from position 1: smallest is N (last position)
# Swap Y and N: H, N, T, P, O, Y

# From position 2: smallest is O (4th position)
# Swap T and O: H, N, O, P, T, Y

# From position 3: P is already smallest
# From position 4: T is smallest
# H, N, O, P, T, Y

# Insertion Sort
# builds the sorted list one item at a time

# Start with just P: [P]
# Add Y: Y > P, so [P, Y]
# Add T: T < Y but T > P, so [P, T, Y]
# Add H: H < Y, H < T, H > P -> [P, H, T, Y]
# Add O: O < Y, O < T, O > H -> [P, H, O, T, Y]
# Add N: N < Y, N < T, N < O, N > H -> [P, H, N, O, T, Y]
# final: H, N, O, P, T, Y

# Merge Sort
# splits everything up then merges it back together sorted.

# Split: [P,Y,T] and [H,O,N]
# Split left: [P] and [Y,T] -> [Y] and [T]
# Split right: [H] and [O,N] -> [O] and [N]

# Now merge back:
# Merge Y and T -> T,Y
# Merge P with T,Y -> P,T,Y

# Merge O and N -> N,O
# Merge H with N,O -> H,N,O

# Final merge: P,T,Y with H,N,O
# Compare P and H -> take H
# Compare P and N -> take N
# Compare P and O -> take O
# Now just add P,T,Y
# Final: H,N,O,P,T,Y

def calculate_stats(numbers):
    # sum
    total = sum(numbers)

    # mean
    mean = total / len(numbers)

    # median
    sorted_nums = sorted(numbers)
    n = len(sorted_nums)

    if n % 2 == 1:
        median = sorted_nums[n // 2]
    else:
        mid1 = sorted_nums[n // 2 - 1]
        mid2 = sorted_nums[n // 2]
        median = (mid1 + mid2) / 2

    # mode
    freq = {}
    for num in numbers:
        if num in freq:
            freq[num] += 1
        else:
            freq[num] = 1

    max_count = max(freq.values())
    mode = [num for num, count in freq.items() if count == max_count]

    if len(mode) == len(numbers):
        mode = "No mode"
    elif len(mode) == 1:
        mode = mode[0]

    print("Numbers:", numbers)
    print("Sum:", total)
    print("Mean:", mean)
    print("Median:", median)
    print("Mode:", mode)

numbers = [5, 2, 8, 2, 5, 1, 9]
calculate_stats(numbers)

def dups(lst):
    seen = []
    duplicates = []

    for item in lst:
        if item in seen and item not in duplicates:
            duplicates.append(item)
        seen.append(item)

    return duplicates


numbers = []
print("Enter elements for the list (type 'ok' when finished):")

while True:
    user_input = input()
    if user_input.lower() == 'ok':
        break
    numbers.append(user_input)


duplicate_elements = dups(numbers)
print()
print("Original list:", numbers)
print("Duplicate elements:", duplicate_elements)

a = [1, 3, 5]
b = [2, 4, 6]

c = a + b

d = sorted(c)

d.reverse()

c[3] = 42

d.append(10)

c.extend([7, 8, 9])

print("First three elements of c:", c[:3])

print("Last element of d:", d[-1])

print("Length of d:", len(d))

print("\nFinal lists:")
print("a =", a)
print("b =", b)
print("c =", c)
print("d =", d)

a = [
    (1,),
    (2, 3),
    (4, 5, 6)
]

print("Second element of second tuple:", a[1][1])

b = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

print("Last two elements of first list:", b[0][-2:])

print("\nList a:", a)
print("List b:", b)

calendar = []

for month in range(12):
    month_weeks = []
    for week in range(4):
        week_days = []
        month_weeks.append(week_days)
    calendar.append(month_weeks)

print("Initial 3D calendar created with nested for loops")
print(f"Calendar structure: {len(calendar)} months, each with {len(calendar[0])} weeks")

month_names = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
]

calendar_dict = {}

for i, month_name in enumerate(month_names):
    month_data = {}
    for week_num in range(1, 5):
        month_data[f"Week {week_num}"] = []
    calendar_dict[month_name] = month_data

print("\nModified calendar with human-readable names:")
print(f"Months available: {list(calendar_dict.keys())}")
print(f"Weeks in July: {list(calendar_dict['July'].keys())}")

calendar_dict["July"]["Week 2"].append("Team meeting")
calendar_dict["July"]["Week 2"].append("Dentist appointment")

print(f"\nEvents in July Week 2: {calendar_dict['July']['Week 2']}")

print("\nComplete calendar structure:")
for month_name, weeks in calendar_dict.items():
    print(f"{month_name}: {list(weeks.keys())}")

