# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114N_IQNzSWTQCq_adTxGW0ao87GNhgAi
"""

# task 1

graph_one = {
    'A': ['B', 'E', 'D'],
    'B': ['A', 'C'],
    'C': ['B'],
    'D': ['A'],
    'E': ['A', 'F'],
    'F': ['E', 'G', 'H'],
    'G': ['F'],
    'H': ['F']
}

graph_two = {
    'A': ['D', 'B'],
    'B': ['C', 'G', 'E'],
    'C': ['A'],
    'D': ['C'],
    'E': ['H'],
    'G': ['F'],
    'H': ['F'],
    'F': []
}


graph_three = {
    'A': ['B','E','F'],
    'B': ['A','F','C'],
    'C': ['B','D','G'],
    'D': ['C','G','H'],
    'E': ['A','F','I'],
    'F': ['A','E','B','I'],
    'G': ['C','D','J','L','K'],
    'H': ['D','L'],
    'I': ['E','F','J','M','N'],
    'J': ['I','G','K'],
    'K': ['J','G','O','N'],
    'L': ['G','H','P'],
    'M': ['I','N'],
    'N': ['M','I','K'],
    'O': ['K','P'],
    'P': ['L','O']


}

# task 2 finding path from one node to another node (done using graph1) as not explicitely mentioned in the question

graph_one = {
    'A': ['B', 'E', 'D'],
    'B': ['A', 'C'],
    'C': ['B'],
    'D': ['A'],
    'E': ['A', 'F'],
    'F': ['E', 'G', 'H'],
    'G': ['F'],
    'H': ['F']
}


visited =[]
queue =[]

def BFS(startingNode,visited,goalnode):
    visited.append(startingNode)
    queue.append(startingNode)
    print("Path is: ")
    while queue:
        node = queue.pop(0)

        print(node, end="->")
        if node in goalnode:
            print()
            print(f"Goal Node Found {node}")
            goalnode.remove(node)
            if not goalnode:
              break

        for child in graph_one[node]:
            if child not in visited:
                visited.append(child)
                queue.append(child)

BFS('A', visited,['F'])

# task 3 finding all possible pathh

graph_one = {
    'A': ['B', 'E', 'D'],
    'B': ['A', 'C'],
    'C': ['B'],
    'D': ['A'],
    'E': ['A', 'F'],
    'F': ['E', 'G', 'H'],
    'G': ['F'],
    'H': ['F']
}



def BFS_find_all_path(start, end):
    """Find all possible paths from start to end using BFS approach"""
    if start == end:
        return [[start]]

    all_paths = []
    queue = []
    queue.append([start])

    while queue:
        current_path = queue.pop(0)
        current_node = current_path[-1]

        if current_node == end:
            all_paths.append(current_path)
            continue

        for neighbor in graph_one[current_node]:
            if neighbor not in current_path:
                new_path = current_path + [neighbor]
                queue.append(new_path)

    return all_paths


print(BFS_find_all_path('A','G'))

# task 4

graph_one = {
    'A': ['B', 'E', 'D'],
    'B': ['A', 'C'],
    'C': ['B'],
    'D': ['A'],
    'E': ['A', 'F'],
    'F': ['E', 'G', 'H'],
    'G': ['F'],
    'H': ['F']
}

graph_two = {
    'A': ['D', 'B'],
    'B': ['C', 'G', 'E'],
    'C': ['A'],
    'D': ['C'],
    'E': ['H'],
    'G': ['F'],
    'H': ['F'],
    'F': []
}


graph_three = {
    'A': ['B','E','F'],
    'B': ['A','F','C'],
    'C': ['B','D','G'],
    'D': ['C','G','H'],
    'E': ['A','F','I'],
    'F': ['A','E','B','I'],
    'G': ['C','D','J','L','K'],
    'H': ['D','L'],
    'I': ['E','F','J','M','N'],
    'J': ['I','G','K'],
    'K': ['J','G','O','N'],
    'L': ['G','H','P'],
    'M': ['I','N'],
    'N': ['M','I','K'],
    'O': ['K','P'],
    'P': ['L','O']


}

graph_one_wh = {
    'A': {'B': 3, 'E': 7, 'D': 2},
    'B': {'A': 3, 'C': 5},
    'C': {'B': 5},
    'D': {'A': 2},
    'E': {'A': 7, 'F': 4},
    'F': {'E': 4, 'G': 6, 'H': 8},
    'G': {'F': 6},
    'H': {'F': 8}
}

graph_two_wh = {
    'A': {'D': 5, 'B': 2},
    'B': {'C': 7, 'G': 3, 'E': 4},
    'C': {'A': 9},
    'D': {'C': 6},
    'E': {'H': 8},
    'G': {'F': 1},
    'H': {'F': 5},
    'F': {}
}

graph_three_wh = {
    'A': {'B': 4, 'E': 2, 'F': 6},
    'B': {'A': 4, 'F': 3, 'C': 5},
    'C': {'B': 5, 'D': 7, 'G': 8},
    'D': {'C': 7, 'G': 2, 'H': 4},
    'E': {'A': 2, 'F': 9, 'I': 3},
    'F': {'A': 6, 'E': 9, 'B': 3, 'I': 5},
    'G': {'C': 8, 'D': 2, 'J': 6, 'L': 7, 'K': 4},
    'H': {'D': 4, 'L': 3},
    'I': {'E': 3, 'F': 5, 'J': 8, 'M': 2, 'N': 6},
    'J': {'I': 8, 'G': 6, 'K': 7},
    'K': {'J': 7, 'G': 4, 'O': 5, 'N': 3},
    'L': {'G': 7, 'H': 3, 'P': 9},
    'M': {'I': 2, 'N': 4},
    'N': {'M': 4, 'I': 6, 'K': 3},
    'O': {'K': 5, 'P': 8},
    'P': {'L': 9, 'O': 8}
}

H_graph_one = {
    'A': 10, 'B': 8, 'C': 7, 'D': 9, 'E': 6, 'F': 4, 'G': 2, 'H': 0
}

H_graph_two = {
    'A': 8, 'B': 6, 'C': 7, 'D': 5, 'E': 4, 'F': 0, 'G': 2, 'H': 3
}

H_graph_three = {
    'A': 15, 'B': 12, 'C': 10, 'D': 8, 'E': 11, 'F': 9, 'G': 6, 'H': 7,
    'I': 5, 'J': 4, 'K': 3, 'L': 5, 'M': 4, 'N': 2, 'O': 3, 'P': 0
}

def BFS1(startingNode, use_graph):
    visited = []
    queue = []
    visited.append(startingNode)
    queue.append(startingNode)
    print("Path is: ")
    while queue:
        node = queue.pop(0)
        print(node, end="->")

        for child in use_graph[node]:
            if child not in visited:
                visited.append(child)
                queue.append(child)
    print()


print("BFS:")
BFS1('A',graph_one)
BFS1('A',graph_two)
BFS1('A',graph_three)



def DFS1(startingNode, use_graph):
    visited = []
    stack = []
    visited.append(startingNode)
    stack.append(startingNode)
    print("Path is: ")
    while stack:
        node = stack.pop()
        print(node, end="->")

        for child in use_graph[node]:
            if child not in visited:
                visited.append(child)
                stack.append(child)
    print()



print()
print("DFS:")
DFS1('A',graph_one)
DFS1('A',graph_two)
DFS1('A',graph_three)




def UCS(start, goal, graph):
    cost = 0
    path = [start]
    visited = []
    queue = [cost, path]

    while queue:
        index = 0
        minIndex = 0
        while index < len(queue):
            if queue[minIndex] > queue[index]:
                minIndex = index
            index = index + 2

        cost = queue.pop(minIndex)
        path = queue.pop(minIndex)
        last = path[-1]

        if last not in visited:
            visited.append(last)
        if last == goal:
            path.append(str(cost))
            return path

        for child in graph[last].keys():
            NewPath = list(path)
            NewPath.append(child)
            queue.append(cost + graph[last][child])
            queue.append(NewPath)

    return None


print()
print("UCS:")
print(UCS('A','G',graph_one_wh))
print(UCS('A','F',graph_two_wh))
print(UCS('A','N',graph_three_wh))
print()




def GBFS(start, goal, graph, heuristic):
    cost = 0
    path = [start]
    visited = []
    queue = [cost, path]

    while queue:
        index = 0
        minIndex = 0

        while index < len(queue):
            current_path = queue[minIndex + 1]
            current_node = current_path[-1]
            current_heuristic = heuristic[current_node]

            compare_path = queue[index + 1]
            compare_node = compare_path[-1]
            compare_heuristic = heuristic[compare_node]

            if current_heuristic > compare_heuristic:
                minIndex = index
            index = index + 2

        cost = queue.pop(minIndex)
        path = queue.pop(minIndex)
        last = path[-1]

        if last not in visited:
            visited.append(last)

        if last == goal:
            return path, cost

        for child in graph[last].keys():
            if child not in visited:
                NewPath = list(path)
                NewPath.append(child)
                queue.append(cost + graph[last][child])
                queue.append(NewPath)

    return None, float('inf')


print("GBFS:")
print(GBFS('A','G',graph_one_wh,H_graph_one))
print(GBFS('A','F',graph_two_wh,H_graph_two))
print(GBFS('A','N',graph_three_wh,H_graph_three))
print()


def A_star(start, goal, graph, heuristic):
    cost = 0
    path = [start]
    visited = []
    queue = [cost, path]

    while queue:
        index = 0
        minIndex = 0

        while index < len(queue):
            current_g = queue[minIndex]
            current_path = queue[minIndex + 1]
            current_last_node = current_path[-1]
            current_f = current_g + heuristic[current_last_node]

            compare_g = queue[index]
            compare_path = queue[index + 1]
            compare_last_node = compare_path[-1]
            compare_f = compare_g + heuristic[compare_last_node]

            if current_f > compare_f:
                minIndex = index
            index = index + 2

        cost = queue.pop(minIndex)
        path = queue.pop(minIndex)
        last = path[-1]

        if last not in visited:
            visited.append(last)

        if last == goal:
            return path, cost

        for child in graph[last].keys():
            if child not in visited:
                NewPath = list(path)
                NewPath.append(child)
                new_cost = cost + graph[last][child]
                queue.append(new_cost)
                queue.append(NewPath)

    return None, float('inf')


print("A*:")
print(A_star('A','G',graph_one_wh,H_graph_one))
print(A_star('A','F',graph_two_wh,H_graph_two))
print(A_star('A','N',graph_three_wh,H_graph_three))

# task 5

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

def selection_sort(arr):
    n = len(arr)
    for i in range(n):
        min_idx = i
        for j in range(i+1, n):
            if arr[j] < arr[min_idx]:
                min_idx = j
        arr[i], arr[min_idx] = arr[min_idx], arr[i]
    return arr

def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i-1
        while j >=0 and key < arr[j]:
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key
    return arr

def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr)//2
        left = arr[:mid]
        right = arr[mid:]

        merge_sort(left)
        merge_sort(right)

        i = j = k = 0

        while i < len(left) and j < len(right):
            if left[i] < right[j]:
                arr[k] = left[i]
                i += 1
            else:
                arr[k] = right[j]
                j += 1
            k += 1

        while i < len(left):
            arr[k] = left[i]
            i += 1
            k += 1

        while j < len(right):
            arr[k] = right[j]
            j += 1
            k += 1
    return arr

chars = ['M','O','H','S','I','N']

print("Original list:", chars)

bubble_result = bubble_sort(chars.copy())
print("Bubble sort:", bubble_result)

selection_result = selection_sort(chars.copy())
print("Selection sort:", selection_result)

insertion_result = insertion_sort(chars.copy())
print("Insertion sort:", insertion_result)

merge_result = merge_sort(chars.copy())
print("Merge sort:", merge_result)