# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

class stack:
  def __init__(self):
    self.items=[]

  def push(self,item):
    self.items.append(item)

  def pop(self):
    if self.isEmpty():
      return None
    else:
      return self.items.pop()

  def isEmpty(self):
       if self.items==[]:
        return True
       else:
        return False

  def peek(self):
      if not self.isEmpty():
        return self.items[-1]
      else:
        return None

  def display(self):
      print(self.items)




my_obj = stack()
my_obj.push(2)
my_obj.push(22)
my_obj.push(23)
my_obj.push(25)
my_obj.push(27)

my_obj.display()

class queue:
  def __init__(self):
    self.items=[]

  def enqueue(self,item):
    self.items.append(item)

  def dequeue(self):
    if self.isEmpty():
      return None
    else:
      return self.items.pop(0)

  def isEmpty(self):
       if self.items==[]:
        return True
       else:
        return False



  def display(self):
      print(self.items)